### ISSUE TITLE
Is there a release planned?

### ISSUE THREAD

**Issue by m3gg3r** [terraform-providers/terraform-provider-bitbucket#13]
There are some changes in the master without a release. Is a release planned in the near future?

**Comment by tombuildsstuff** [comment]
Hey @m3gg3r 

Thanks for raising this - I've reached out to @cwood just to double-check that's fine - with the intention of shipping a release early next week :)

Thanks!

**Comment by tombuildsstuff** [comment]
Hey @m3gg3r 

Just to let you know that I've just released v1.0.0 of the BitBucket provider :)

Thanks!
