### ISSUE TITLE
Question: Is BitBucket Server supported or just BitBucket Cloud?

### ISSUE THREAD

**Issue by kmcquade** [terraform-providers/terraform-provider-bitbucket#18]
There aren't options to set a server URL in the provider config; I take this to mean that only BitBucket cloud is supported. Are there any plans to support BitBucket Server?

Thanks

**Comment by cwood** [comment]
This is just bitbucket cloud and not server.

**Comment by rumpunch** [comment]
@cwood are there any plans for supporting bitbucket server? My company enterprise client of both TF and Atlassian tools, is this something we can request to be supported by this provider?

**Comment by gavinbunney** [comment]
In the absence of official support, I've started working on a bitbucket server provider - it currently supports most of the key API components as resources or data sources: https://github.com/gavinbunney/terraform-provider-bitbucketserver
