### ISSUE TITLE
Feature request: Pipelines settings and repository variables

### ISSUE THREAD

**Issue by KimSamba** [terraform-providers/terraform-provider-bitbucket#38]
Hi there,

It would be nice to be able to set pipelines for a bunch of projects (pretty useful when a lot of repo needs AWS keys, npm token etc...).

It would be awesome because currently, this must be done manually, and could be nicely automated with Terraform (AWS SSM to inject into BP, integration test where i need to configure the endpoint, which could be easily used updated from terraform output etc.)

### Terraform Version
v0.12.2

**Comment by hronix** [comment]
Yes, please

**Comment by tdi** [comment]
Hi   - I am working on a PR for this but bitbucket API has not offered this functionality (yeah hard to believe right?). However, according to this issue https://jira.atlassian.com/browse/BCLOUD-18164 - somebody has discovered some hidden endpoint for it. I will investingate this over the following weeks and try to get back here.

**Comment by KimSamba** [comment]
How about this endpoint?
https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/environments/
This is for environment variables

**Comment by tdi** [comment]
Environment variables I have ready. Same for ssh keys. Give me some time to prepare a PR for env only.

**Comment by tdi** [comment]
hi see #41 . I added repository variables  and enabling pipelines in repo.

**Comment by tdi** [comment]
Unfortunatelly I used the wrong API endpoint that at the time of writing the software worked. https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/
and 
https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-workspaces/
