### ISSUE TITLE
Feature request: support for branch policies

### ISSUE THREAD

**Issue by mahpatil** [terraform-providers/terraform-provider-bitbucket#44]
Feature request
### Terraform Version
Terraform v0.12.17

### Feature requested
Support for branch policies, the feature should allow creating a standard set of policy variants that can be applied at a per-repository/project level (if possible)

### Bitbucket API
https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/branch-restrictions

**Comment by amatellanes** [comment]
Hi @mahpatil,

The branch restrictions feature has just been added to the new version 1.2.0 More info [here](https://www.terraform.io/docs/providers/bitbucket/r/branch_restriction.html).

**Comment by pjroth** [comment]
@mahpatil it looks like this can be closed per @amatellanes comment that version 1.2.0 has the ability to set branch_restrictions ([name per API](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/branch-restrictions)) do you agree?  Although the bitbucket website calls them "Branch Permissions" under repository settings confusingly.  They seem to be the same thing though.  

You stated "branch policies" however so it could be you are talking about something different than what has already been implemented?

**Comment by mahpatil** [comment]
Yes. Thanks @pjroth and @amatellanes
