### ISSUE TITLE
repository variables failing to create

### ISSUE THREAD

**Issue by ghost** [terraform-providers/terraform-provider-bitbucket#53]
Creating a bitbucket_repository_variable fails with API 403 error. Plan works fine

 \# module.test.bitbucket_repository_variable.test will be created
  + resource "bitbucket_repository_variable" "test" {
      + id         = (known after apply)
      + key        = "test"
      + repository = "xxxx/test"
      + secured    = false
      + uuid       = (known after apply)
      + value      = "test"
    }

### Terraform Version
Terraform v0.12.21
+ provider.bitbucket v1.2.0

### Affected Resource(s)
bitbucket_repository_variable

### Terraform Configuration Files

provider "bitbucket" {
  username = "xxxxxx"
  password = var.password
}

resource "bitbucket_repository_variable" "test" {
  key        = "test"
  value      = "test"
  repository = bitbucket_repository.test.id
  secured    = false
}

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
bitbucket repository variable created

### Actual Behavior
Error: API Error: 403 2.0/repositories/xxxxxx/test/pipelines_config/variables/ Your credentials lack one or more required privilege scopes.

User has admin permissions to the repo and to the organization

**Comment by w0ut0** [comment]
Hi @rupertohpen, I had a similar issue and problem was that I didn't assign the correct permissions when creating the app password (the user was an admin, but the app password I was using had limited permissions).
Hope this helps!

**Comment by ghost** [comment]
@w0ut0 thanks for the hint - i thought I checked that but I'll double check

**Comment by ghost** [comment]
@w0ut0 was correct
